# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-deploy-spacelift
  description: Deploy Docker image application with Spacelift
  homepage: https://cloudposse.com/accelerate
  topics: ""
